### ISSUE TITLE
The extension context does not have a method with the name init.

### ISSUE THREAD

**Issue by diontoradan** [pozirk/ANEAdMob#1]
[SWF] com.pozirk.ads.AdMob - 6105 bytes after decompression
[SWF] tes.swf - 2682 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name init.
    at flash.external::ExtensionContext/_call()
    at flash.external::ExtensionContext/call()
    at com.pozirk.ads.admob::AdMob/init()[D:\Pozirk_projects\ANEAdMob\air\AdMob\com\pozirk\ads\admob\AdMob.as:43]
    at tes_fla::MainTimeline/frame1()[tes_fla.MainTimeline::frame1:18]
    at runtime::ContentPlayer/loadInitialContent()
    at runtime::ContentPlayer/playRawContent()
    at runtime::ContentPlayer/playContent()
    at runtime::AppRunner/run()
    at ADLAppEntry/run()
    at global/runtime::ADLEntry()

**Comment by Nuflan** [comment]
whats this error can you help me please im using windows 10
AIR 30.0.0.107 for android
adobe flash cc 2017

//output


[SWF] com.pozirk.ads.AdMob - 7065 bytes after decompression
[SWF] Untitled-2.swf - 6682 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name cacheInterstitial.
at flash.external::ExtensionContext/_call()
at flash.external::ExtensionContext/call()
at com.pozirk.ads.admob::AdMob/cacheInterstitial()[D:\Pozirk\_projects\ANEAdMob\air\AdMob\com\pozirk\ads\admob\AdMob.as:83]
at Main()[C:\Users\user\Desktop\admob\Main.as:43]
at runtime::ContentPlayer/loadInitialContent()
at runtime::ContentPlayer/playRawContent()
at runtime::ContentPlayer/playContent()
at runtime::AppRunner/run()
at ADLAppEntry/run()
at global/runtime::ADLEntry()
Test Movie terminated.

// code
package  {
	
	import flash.display.MovieClip;
	
	import com.pozirk.ads.admob.AdMob;
	import com.pozirk.ads.admob.AdParams;
	import com.pozirk.ads.admob.AdEvent;
	import flash.events.MouseEvent;
	
	public class Main extends MovieClip {
		
		private var _bannerAdUID:String = "ca-app-pub-6896619151286612/6300978111";
		private var _intersAdUID:String = "ca-app-pub-3940256099942544/1033173712";
		protected var _banner:AdMob = new AdMob();
		protected var _inters:AdMob = new AdMob();
		private var _initOK:Boolean = false;
		private var _isShow:Boolean = false;
		private var _cacheOK:Boolean = false;
		public function Main() {
			// constructor code
			btBanner.addEventListener(MouseEvent.CLICK, showBanner);
			btInters.addEventListener(MouseEvent.CLICK, showInterstitial);
			_banner.init();
			_banner.addEventListener(AdEvent.INIT_OK, onInitEvent);
			_banner.addEventListener(AdEvent.INIT_FAIL, onEvent);
			_banner.addEventListener(AdEvent.BANNER_SHOW_OK, onEvent);
            _banner.addEventListener(AdEvent.BANNER_SHOW_FAIL, onEvent);
			_banner.addEventListener(AdEvent.BANNER_LEFT_APP, onEvent);
			_banner.addEventListener(AdEvent.BANNER_OPENED, onEvent);
			_banner.addEventListener(AdEvent.BANNER_CLOSED, onEvent);
			
			_inters.init();
			_inters.addEventListener(AdEvent.INIT_OK, onInitEvent);
			_inters.addEventListener(AdEvent.INIT_FAIL, onEvent);
			_inters.addEventListener(AdEvent.INTERSTITIAL_SHOW_OK, onEvent);
			_inters.addEventListener(AdEvent.INTERSTITIAL_SHOW_FAIL, onEvent);
			_inters.addEventListener(AdEvent.INTERSTITIAL_CACHE_OK, onCacheEvent); 
			_inters.addEventListener(AdEvent.INTERSTITIAL_CACHE_FAIL, onEvent); 
			_inters.addEventListener(AdEvent.INTERSTITIAL_LEFT_APP,onEvent);
			_inters.addEventListener(AdEvent.INTERSTITIAL_OPENED, onEvent);
			_inters.addEventListener(AdEvent.INTERSTITIAL_CLOSED, onCloseIntersEvent);
			
			_inters.cacheInterstitial(_intersAdUID);
			
			}
			
			protected function onEvent(event:AdEvent):void{}
			protected function onInitEvent(event:AdEvent):void{
                   _initOK = true;				
				}
			protected function onCacheEvent(event:AdEvent):void{
				    _cacheOK = true;
				}
			protected function onCloseIntersEvent(event:AdEvent):void{
				    _inters.cacheInterstitial(_intersAdUID);
				}
				
			private function showBanner(event:MouseEvent):void{
				if(_initOK){
					
					if(!_isShow)
					{
						_banner.show(_bannerAdUID, AdParams.SIZE_SMART_BANNER, AdParams.HALIGN_CENTER, AdParams.VALIGN_BOTTOM)
						_isShow = true;
						
						
						}
					else
					{
						_banner.hide();
						_isShow = false;
						}
					
					}
					else
					{
						trace("banner not ready");
						}
				
				}
				
				private function showInterstitial(event:MouseEvent):void
				{
					if(_initOK && _cacheOK)
					{
                         			_inters.showInterstitial();			
						}
						else
						{
							trace("inters not ready");
							}
					
					}
	}
	
}

i publish and try it it doesnot work.... please help me
