### ISSUE TITLE
Google Play Services version

### ISSUE THREAD

**Issue by ekilah** [pozirk/ANEAdMob#15]
Is there a way we can avoid this line in the manifest, and instead actually access the value of the version of GPS from the SDK itself? Seems like this is a bug and was never resolved (copied from the README):

```
<meta-data android:name="com.google.android.gms.version" android:value="4323000" /> <!-- should be android:value="@integer/google_play_services_version" -->
```

**Comment by pozirk** [comment]
I don't know, how to make admob works without this line.
If you need to use a newer google play server, simple put different version number.
This is not a bug.

**Comment by ekilah** [comment]
I'm not sure how to either, was just curious if anyone did. I guess it's not a bug but something that could be improved, if possible. Maybe it's not possible.

**Comment by khunglongcon** [comment]
Issues in here android:value="4323000"
You can't change any google service version. If you put android:value="@integer/google_play_services_version" => The app can not be built. 
If you put a determined value like android:value=8489470 => App will be built, but Ads not show and console throw a log "The meta-data tag in your app's AndroidManifest.xml does not have the right value. Expected 4323000 but found 8489470".......

**Comment by pozirk** [comment]
You can, if you use different version number, you should use different google play service as well.

**Comment by pozirk** [comment]
I have updated ANE to version "8487000".
