### ISSUE TITLE
Upgrade to Google Mobile Ads SDK 7.0.0 or higher

### ISSUE THREAD

**Issue by VadimPecherskii** [pozirk/ANEAdMob#16]
I've got a message from Google Play:
"In order to ensure that your ads continue to serve after September 15th, 2016, please upgrade to Google Mobile Ads SDK 7.0.0 or higher."
How can I do this? Whatever parameter I set in app.xml (com.google.android.gms.version) it either doesn't show ads or doesn't work. The only one that works for me is 4323000. 
I updated FlashDevelop, Air, Android SDK but it seems it doesn't help.
Could you advise anything?

**Comment by pozirk** [comment]
Current version of ANE should be good enough, also I will update to a newer version soon.

**Comment by Pecher** [comment]
Thanks, looking forward to it!

**Comment by Pecher** [comment]
Which Android API level do you use in projects with this ANE? I tried to use Android 4.0 (API 14), Air 22.

**Comment by pozirk** [comment]
Actually, ANE is already the latest version, I've updated it 4 months ago and forgot about this, :)
It's AIRSDK 23 and Android API 23.
