### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name cacheInterstitial.

### ISSUE THREAD

**Issue by Nuflan** [pozirk/ANEAdMob#18]
whats this error can you help me please im using windows 10
AIR 30.0.0.107 for android
adobe flash cc 2017

//output

[SWF] com.pozirk.ads.AdMob - 7065 bytes after decompression
[SWF] Untitled-2.swf - 6682 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name cacheInterstitial.
at flash.external::ExtensionContext/_call()
at flash.external::ExtensionContext/call()
at com.pozirk.ads.admob::AdMob/cacheInterstitial()[D:\Pozirk_projects\ANEAdMob\air\AdMob\com\pozirk\ads\admob\AdMob.as:83]
at Main()[C:\Users\user\Desktop\admob\Main.as:43]
at runtime::ContentPlayer/loadInitialContent()
at runtime::ContentPlayer/playRawContent()
at runtime::ContentPlayer/playContent()
at runtime::AppRunner/run()
at ADLAppEntry/run()
at global/runtime::ADLEntry()
Test Movie terminated.

// code
package {

import flash.display.MovieClip;

import com.pozirk.ads.admob.AdMob;
import com.pozirk.ads.admob.AdParams;
import com.pozirk.ads.admob.AdEvent;
import flash.events.MouseEvent;

public class Main extends MovieClip {
	
	private var _bannerAdUID:String = "ca-app-pub-6896619151286612/6300978111";
	private var _intersAdUID:String = "ca-app-pub-3940256099942544/1033173712";
	protected var _banner:AdMob = new AdMob();
	protected var _inters:AdMob = new AdMob();
	private var _initOK:Boolean = false;
	private var _isShow:Boolean = false;
	private var _cacheOK:Boolean = false;
	public function Main() {
		// constructor code
		btBanner.addEventListener(MouseEvent.CLICK, showBanner);
		btInters.addEventListener(MouseEvent.CLICK, showInterstitial);
		_banner.init();
		_banner.addEventListener(AdEvent.INIT_OK, onInitEvent);
		_banner.addEventListener(AdEvent.INIT_FAIL, onEvent);
		_banner.addEventListener(AdEvent.BANNER_SHOW_OK, onEvent);
        _banner.addEventListener(AdEvent.BANNER_SHOW_FAIL, onEvent);
		_banner.addEventListener(AdEvent.BANNER_LEFT_APP, onEvent);
		_banner.addEventListener(AdEvent.BANNER_OPENED, onEvent);
		_banner.addEventListener(AdEvent.BANNER_CLOSED, onEvent);
		
		_inters.init();
		_inters.addEventListener(AdEvent.INIT_OK, onInitEvent);
		_inters.addEventListener(AdEvent.INIT_FAIL, onEvent);
		_inters.addEventListener(AdEvent.INTERSTITIAL_SHOW_OK, onEvent);
		_inters.addEventListener(AdEvent.INTERSTITIAL_SHOW_FAIL, onEvent);
		_inters.addEventListener(AdEvent.INTERSTITIAL_CACHE_OK, onCacheEvent); 
		_inters.addEventListener(AdEvent.INTERSTITIAL_CACHE_FAIL, onEvent); 
		_inters.addEventListener(AdEvent.INTERSTITIAL_LEFT_APP,onEvent);
		_inters.addEventListener(AdEvent.INTERSTITIAL_OPENED, onEvent);
		_inters.addEventListener(AdEvent.INTERSTITIAL_CLOSED, onCloseIntersEvent);
		
		_inters.cacheInterstitial(_intersAdUID);
		
		}
		
		protected function onEvent(event:AdEvent):void{}
		protected function onInitEvent(event:AdEvent):void{
               _initOK = true;				
			}
		protected function onCacheEvent(event:AdEvent):void{
			    _cacheOK = true;
			}
		protected function onCloseIntersEvent(event:AdEvent):void{
			    _inters.cacheInterstitial(_intersAdUID);
			}
			
		private function showBanner(event:MouseEvent):void{
			if(_initOK){
				
				if(!_isShow)
				{
					_banner.show(_bannerAdUID, AdParams.SIZE_SMART_BANNER, AdParams.HALIGN_CENTER, AdParams.VALIGN_BOTTOM)
					_isShow = true;
					
					
					}
				else
				{
					_banner.hide();
					_isShow = false;
					}
				
				}
				else
				{
					trace("banner not ready");
					}
			
			}
			
			private function showInterstitial(event:MouseEvent):void
			{
				if(_initOK && _cacheOK)
				{
                     			_inters.showInterstitial();			
					}
					else
					{
						trace("inters not ready");
						}
				
				}
}
}

i publish and try it it doesnot work.... please help me

**Comment by pozirk** [comment]
This is Android extension, it's not working on Desktop.

**Comment by etmgames** [comment]
i m using animate 2017.1 and air sdk 28. compiling apk. uploading to the samsung s9+  ads not displaying. xml is ok. what is the problem

**Comment by pozirk** [comment]
How should I know what is the problem?

**Comment by etmgames** [comment]
Privet Igor eshe raz. Please help me. i did not change nothing. what can be problem i dont know. 
xml like this:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/28.0">
  <id>deneme</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>deneme</filename>
  <description/>
  <name>deneme</name>
  <copyright/>
  <initialWindow>
    <content>deneme.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
        <manifestAdditions><![CDATA[
        <manifest android:installLocation="auto">
                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
                <application>
     				<meta-data android:name="com.google.android.gms.version" android:value="11020000"/>
                    <activity android:name="com.google.android.gms.ads.AdActivity"
                    android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
                    android:theme="@android:style/Theme.Translucent" />
				</application>

        </manifest>]]></manifestAdditions>
    </android>



  <extensions>
    <extensionID>com.pozirk.ads.AdMob</extensionID>
  </extensions>
</application>

**Comment by pozirk** [comment]
Может у тебя просто "no fill", попробуй тетстовую рекламу.

**Comment by etmgames** [comment]
one year ago uploaded this app and working with same sdk (air sdk 28) animate 2017.1 and same xml
https://play.google.com/store/apps/details?id=air.BabyElephantSalon

i am trying to compile same app again with same programme, sdk again, then installing to my samsung galaxy s9+ ads not display.  what do you mean "no fill" ? i would be grateful if you can help me. because trying to solve problem since a week

**Comment by pozirk** [comment]
check logs, how could I know what the problem?
"no fill" means admob has no ads to serve.

**Comment by etmgames** [comment]
But, when i install same app from google.play ad showing.

**Comment by etmgames** [comment]
just need help to solve problem.

**Comment by pozirk** [comment]
Check logs.

**Comment by etmgames** [comment]
where is the logs?

**Comment by etmgames** [comment]
i am using adobe animate 2017.1

**Comment by etmgames** [comment]
i used google test ads and ads displaying. so everything is ok.
