### ISSUE TITLE
Anyone Please Help, admob ad not shown by using orginal ID

### ISSUE THREAD

**Issue by sahanasalim** [pozirk/ANEAdMob#21]
I used lot of ANE for admob , im using flash cc and coding done by AS3(Action Script 3).
I can successfully run code & take Apk for Android devices, And I got test ad after run my apk in android devices.
When i use orginal ad ID i didnt get any ad i got message like Failed to load interstitial ad from the other side.
i used flash animate 2017 also but result is same.
i dont get any ad by using orginal id, this is happend some days before. my All Android live Apps in playstore are working and this issues happens when i take new apk for update game or new game apks.PLEASE HELP ANYONE....

**Comment by Gusher** [comment]
Are you using test admob id?

**Comment by pozirk** [comment]
If test ads are working, then everything is fine.
You might just have "no fill" for real ads.
