### ISSUE TITLE
AIR 33

### ISSUE THREAD

**Issue by hadisn** [pozirk/ANEAdMob#22]
What will happen with ongoing air update, are you going to support 64-bit version in future. 

https://theblog.adobe.com/the-future-of-adobe-air/

**Comment by pozirk** [comment]
I think, yes, if it won't be a big problem to support 64bit.

**Comment by hadisn** [comment]
Hi friend, i keep my app update rejected due to Issue: Violation of Interfering with Apps, Third-party Ads, or Device Functionality policy. Are you experienced similiar problem, i am asking you since i think you have more experience with this. I can send you link to my app so you can see if you want.

Thanks

**Comment by alphatwin** [comment]
Do you work currently on 64 Bit version?

**Comment by pozirk** [comment]
I have updated to AIR SDK 33, there is 32 and 64 bit versions of ANE now.
32-bit works fine, but I can't test 64-bit version, cause I have no 64-bit device.

**Comment by hadisn** [comment]
I will test and let you know. Thank you

**Comment by hadisn** [comment]
---------------------------
Adobe Animate
---------------------------
Error creating files.

Included native extension 'com.pozirk.ads.AdMob' specifies namespace 'http://ns.adobe.com/air/extension/33.0' which is greater than the application namespace: http://ns.adobe.com/air/application/32.0


---------------------------
OK   
---------------------------

**Comment by hadisn** [comment]
Ok i replaced following line in ane's extension.xml file:
<extension xmlns="http://ns.adobe.com/air/extension/33.0"> 

to:

<extension xmlns="http://ns.adobe.com/air/extension/32.0">

and it works on my android device, but i am not sure is this correct way to fix this. 
I use Adobe Animate CC 2017

**Comment by pozirk** [comment]
You have to use AIR SDK 33 to build 64bit version of the app, don't modify extension.

**Comment by hadisn** [comment]
I used, but in airsdk.xml in air33 is 
`<descriptorNamespace>http://ns.adobe.com/air/application/32.0</descriptorNamespace>`

**Comment by pozirk** [comment]
Strange, I don't have this problem.

**Comment by pozirk** [comment]
I have changed AIR SDK number to 32.

**Comment by pozirk** [comment]
ANE was tested on x64 Android device by some good guy, and he told me it worked fine. :)
