### ISSUE TITLE
Single ANE for ARM and ARM64 versions

### ISSUE THREAD

**Issue by hadisn** [pozirk/ANEAdMob#23]
One suggestion, you should make single ane with both ARM and ARM64 platform so users will be able to add it to Android APP Bundle required by Google. 

I have done it already i can help you if needed.

Regards

**Comment by pozirk** [comment]
Sure, make a commit to the repository.
Thank you!

**Comment by hadisn** [comment]
It is simple, here is how extensions.xml file should looks like:
`<extension xmlns="http://ns.adobe.com/air/extension/32.0">
  <id>com.pozirk.ads.AdMob</id>
  <versionNumber>1</versionNumber>
  <platforms>		
  <platform name="Android-ARM">
      <applicationDeployment>
        <nativeLibrary>libAdMob.jar</nativeLibrary>
        <initializer>com.pozirk.ads.admob.Extension</initializer>
        <finalizer>com.pozirk.ads.admob.Extension</finalizer>
      </applicationDeployment>
    </platform>
		<platform name="Android-ARM64">
      <applicationDeployment>
        <nativeLibrary>libAdMob.jar</nativeLibrary>
        <initializer>com.pozirk.ads.admob.Extension</initializer>
        <finalizer>com.pozirk.ads.admob.Extension</finalizer>
      </applicationDeployment>
    </platform>
		
		<platform name="default">
			<applicationDeployment/>
    </platform> 
  </platforms>
</extension>`

And you need put Android-ARM64 folder from 64bit ane together with Android-ARM folder in META-INF\ANE\

**Comment by jeuxdaily** [comment]
hello
I have a simple code with Milkmangame Native extension but it's doesn't support 64bit
so I need your help to switch Milkmangame Native extension to pozirk ANEAdMob
I try your exemple without any result
thanks
