### ISSUE TITLE
64bit ANE did not work

### ISSUE THREAD

**Issue by Tpman** [pozirk/ANEAdMob#25]
Hi.
Thanks for your good ANE.
In Android 32bit ANE works fine, but 64bit ANE did not work.

The logtrace in scout is below.

Error! ANE was not properly added to your project.
INIT_FAIL ANE was not properly added to your project.

![image](https://user-images.githubusercontent.com/13846098/80862048-308d0300-8cad-11ea-8ae2-63cb3ea62c75.png)
[FD package screenshot]

![image](https://user-images.githubusercontent.com/13846098/80862111-75189e80-8cad-11ea-8818-6bd6d72052af.png)
[Apk package screenshot]

I expect ANE to work fine on 64bit OS.

Thanks.

**Comment by jeuxdaily** [comment]
hi
can you get your code
thanks

**Comment by pozirk** [comment]
ANE is working fine for 64bit Android.
It is said in your screenshot, that you are using wrong version of ANE.
You must use 32 version for 32bit Android, and 64 version for 64bit Android.
