### ISSUE TITLE
The Interstitial not display

### ISSUE THREAD

**Issue by jeuxdaily** [pozirk/ANEAdMob#27]
hi
I create a simple ads with your example
and I have succeed to display Banner
but the interstitial not display
can you help me to get the good code to display Interstitial
thanks

**Comment by pozirk** [comment]
Hi!
I have no idea, what is not working for you.
Check your device logs, all the required code is in readme file.

**Comment by jeuxdaily** [comment]
hi
The INTERSTITIAL NOT DISPLAY In The Game
it's that clear
thanks

**Comment by pozirk** [comment]
Try test interstitial.
Usual real ads are not showing in debug version of the app..
