### ISSUE TITLE
Extension ID in xml issue

### ISSUE THREAD

**Issue by kingbaggot** [pozirk/ANEAdMob#34]
Hi - I've been putting 
`<extensionID>com.pozirk.ads.admob</extensionID> `
in my xml and building from a bat file but it's not finding the ane - I get 'an implementation for native extension 'com.pozirk.ads.admob' req. by the application was not found for this platform.

Here's my my build.xml - https://justpaste.it/6v1kz

Thanks for working on the ane - I thought I was the last Air app builder in town !

**Comment by kingbaggot** [comment]
scratch that. It builds now - athough I get a lot of errors 
Warning:Resource values -sw/values-uk.xml has been skipped because of mismatch with supported languages information in application descriptor (one of these for each lang)

I can't get a banner to appear yet, but will keep trying as it's no doubt something to do with my 64bit settings.

**Comment by pozirk** [comment]
:+1:
