### ISSUE TITLE
Interstitial crash

### ISSUE THREAD

**Issue by kingbaggot** [pozirk/ANEAdMob#35]
Hi Pozirk- thanks for the ane - I have banners working fine now.

Unfortunately, the interstitial crashes the app on showInterstitial() - even with a testId.

It calls cacheInterstitial() successfully though, which is good.

Has anyone else found a fix for this ? I'll try it on some other devices in the meantime - currently the crash bug is on a pixel2

thanks !

**Comment by luc4smoreira** [comment]
Hi @kingbaggot 

What is the error message? Can you post the stack trace?

**Comment by kingbaggot** [comment]
hi @luc4smoreira - thanks for the response.
This is what logcat picks up - I can't get anything directly from the app . Does this help ?

<<< log_count = 25 >>>
[09-02 10:12:07.049 1266:5457 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=air.com.gtoilet.twist/.AppEntry bnds=[237,337][439,590]} from uid 10054

[09-02 10:12:07.050 2102:2162 W/s.nexuslaunche]
resources.arsc in APK '/data/app/air.com.gtoilet.twist-ceJY1fY3kyVBMRMTF4Hmew==/base.apk' is compressed.

[09-02 10:12:07.074 1266:1304 I/ActivityManager]
Start proc 14079:air.com.gtoilet.twist/u0a505 for activity {air.com.gtoilet.twist/air.com.gtoilet.twist.AppEntry}

[09-02 10:12:07.114 14079:14079 W/m.gtoilet.twis]
resources.arsc in APK '/data/app/air.com.gtoilet.twist-ceJY1fY3kyVBMRMTF4Hmew==/base.apk' is compressed.

[09-02 10:12:07.579 628:628 E/Layer]
[Surface(name=AppWindowToken{d18b88d token=Token{c86e524 ActivityRecord{10c19b7 u0 air.com.gtoilet.twist/.AppEntry t19556}}})/@0x82fb4bc - animation-leash#0] No local sync point found

[09-02 10:12:07.849 14079:14116 W/m.gtoilet.twis]
ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/air.com.gtoilet.twist-ceJY1fY3kyVBMRMTF4Hmew==/base.apk*426656243])

[09-02 10:12:07.849 14079:14116 W/m.gtoilet.twis]
Found duplicated class when checking oat files: 'Landroidx/annotation/Keep;' in /data/user_de/0/com.google.android.gms/app_chimera/m/000001c7/dl-AdsFdrDynamite.integ_22060100000.apk and /data/app/air.com.gtoilet.twist-ceJY1fY3kyVBMRMTF4Hmew==/base.apk

[09-02 10:12:08.022 14079:14124 I/FA]
To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app air.com.gtoilet.twist

[09-02 10:12:08.143 1266:1302 I/ActivityTaskManager]
Displayed air.com.gtoilet.twist/.AppEntry: +1s93ms

[09-02 10:12:08.626 1266:1304 I/ActivityManager]
Start proc 14173:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0/u0i461 for  {air.com.gtoilet.twist/org.chromium.content.app.SandboxedProcessService0}

[09-02 10:12:08.736 14173:14198 W/ProcessService]
resources.arsc in APK '/data/app/air.com.gtoilet.twist-ceJY1fY3kyVBMRMTF4Hmew==/base.apk' is compressed.

[09-02 10:12:08.893 2859:11858 W/gle.android.gm]
resources.arsc in APK '/data/app/air.com.gtoilet.twist-ceJY1fY3kyVBMRMTF4Hmew==/base.apk' is compressed.

[09-02 10:12:16.544 1266:3049 I/ActivityTaskManager]
START u0 {cmp=air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity (has extras)} from uid 10505

[09-02 10:12:16.558 1266:15276 W/ActivityTaskManager]
Duplicate finish request for ActivityRecord{10c19b7 u0 air.com.gtoilet.twist/.AppEntry t19556 f}

[09-02 10:12:16.780 1266:1426 W/InputDispatcher]
channel '3f95ee8 air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[09-02 10:12:16.780 1266:1426 E/InputDispatcher]
channel '3f95ee8 air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[09-02 10:12:16.785 1266:1426 W/InputDispatcher]
channel '78fb9f air.com.gtoilet.twist/air.com.gtoilet.twist.AppEntry (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[09-02 10:12:16.785 1266:1426 E/InputDispatcher]
channel '78fb9f air.com.gtoilet.twist/air.com.gtoilet.twist.AppEntry (server)' ~ Channel is unrecoverably broken and will be disposed!

[09-02 10:12:16.787 1266:3049 I/WindowManager]
WIN DEATH: Window{3f95ee8 u0 air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity}

[09-02 10:12:16.787 1266:3049 W/InputDispatcher]
Attempted to unregister already unregistered input channel '3f95ee8 air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity (server)'

[09-02 10:12:16.788 1266:6204 I/ActivityManager]
Process air.com.gtoilet.twist (pid 14079) has died: fore TOP 

[09-02 10:12:16.789 1266:9195 I/WindowManager]
WIN DEATH: Window{78fb9f u0 air.com.gtoilet.twist/air.com.gtoilet.twist.AppEntry}

[09-02 10:12:16.789 1266:9195 W/InputDispatcher]
Attempted to unregister already unregistered input channel '78fb9f air.com.gtoilet.twist/air.com.gtoilet.twist.AppEntry (server)'

[09-02 10:12:16.794 1266:9195 E/InputDispatcher]
Window handle Window{3f95ee8 u0 air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity} has no registered input channel

[09-02 10:12:16.794 1266:6204 W/ActivityTaskManager]
Force removing ActivityRecord{3163682 u0 air.com.gtoilet.twist/com.google.android.gms.ads.AdActivity t19556}: app died, no saved state
